const INITIAL_NOTES = [
  {
    id: "note_001",
    title: "Morning Routine",
    text: "Wake up at 6 AM, meditate for 10 minutes, exercise for 30 minutes, and have a healthy breakfast. This routine has improved my productivity significantly.",
    category: "personal",
    createdAt: "2024-01-15T08:30:00.000Z",
  },
  {
    id: "note_002",
    title: "Books to Read",
    text: "1. Atomic Habits by James Clear\n2. Deep Work by Cal Newport\n3. The Psychology of Money by Morgan Housel\n4. Thinking, Fast and Slow by Daniel Kahneman",
    category: "personal",
    createdAt: "2024-01-16T10:15:00.000Z",
  },
  {
    id: "note_003",
    title: "Grocery List",
    text: "Milk, eggs, bread, fruits (apples, bananas), vegetables (spinach, tomatoes, onions), chicken breast, rice, olive oil, and coffee beans.",
    category: "personal",
    createdAt: "2024-01-17T09:00:00.000Z",
  },
  {
    id: "note_004",
    title: "Birthday Gift Ideas",
    text: "For Mom: A nice scarf or a cooking book. For Dad: New golf clubs or a smartwatch. For Sister: Concert tickets or a spa gift card.",
    category: "personal",
    createdAt: "2024-01-18T14:20:00.000Z",
  },
  {
    id: "note_005",
    title: "Fitness Goals 2024",
    text: "Run a half marathon by June. Do 50 push-ups without stopping. Lose 5 kg by April. Join a yoga class twice a week.",
    category: "personal",
    createdAt: "2024-01-19T07:45:00.000Z",
  },
  {
    id: "note_006",
    title: "Travel Bucket List",
    text: "Japan (cherry blossom season), Iceland (northern lights), New Zealand (hiking), Italy (food tour), Greece (island hopping).",
    category: "personal",
    createdAt: "2024-01-20T16:30:00.000Z",
  },
  {
    id: "note_007",
    title: "Recipe: Pasta Carbonara",
    text: "Ingredients: spaghetti, eggs, parmesan, guanciale, black pepper. Cook pasta, fry guanciale, mix eggs with cheese, combine everything off heat.",
    category: "personal",
    createdAt: "2024-01-21T12:00:00.000Z",
  },
  {
    id: "note_008",
    title: "Home Improvement Tasks",
    text: "Fix the leaky faucet in the bathroom. Paint the bedroom walls. Organize the garage. Install new light fixtures in the living room.",
    category: "personal",
    createdAt: "2024-01-22T11:30:00.000Z",
  },
  {
    id: "note_009",
    title: "Meditation Notes",
    text: "Focus on breath. When mind wanders, gently bring it back. Start with 5 minutes, gradually increase. Best time is early morning or before bed.",
    category: "personal",
    createdAt: "2024-01-23T06:00:00.000Z",
  },
  {
    id: "note_010",
    title: "Movies to Watch",
    text: "Oppenheimer, Dune Part 2, The Shawshank Redemption (rewatch), Interstellar (rewatch), new Studio Ghibli releases.",
    category: "personal",
    createdAt: "2024-01-24T20:15:00.000Z",
  },
  {
    id: "note_011",
    title: "Language Learning Progress",
    text: "Spanish: 30 days streak on Duolingo. Can introduce myself and order food. Next goal: watch a Spanish movie without subtitles.",
    category: "personal",
    createdAt: "2024-01-25T18:45:00.000Z",
  },
  {
    id: "note_012",
    title: "Weekly Meal Plan",
    text: "Monday: Grilled chicken. Tuesday: Pasta. Wednesday: Fish tacos. Thursday: Stir fry. Friday: Pizza night. Weekend: Cooking experiments!",
    category: "personal",
    createdAt: "2024-01-26T10:00:00.000Z",
  },
  {
    id: "note_013",
    title: "Self-Care Reminders",
    text: "Take breaks during work. Stay hydrated. Get 7-8 hours of sleep. Call friends and family regularly. Spend time in nature.",
    category: "personal",
    createdAt: "2024-01-27T09:30:00.000Z",
  },
  {
    id: "note_014",
    title: "Podcast Recommendations",
    text: "1. Huberman Lab - Science\n2. How I Built This - Business\n3. Radiolab - Stories\n4. The Daily - News\n5. Conan Needs a Friend - Comedy",
    category: "personal",
    createdAt: "2024-01-28T15:00:00.000Z",
  },
  {
    id: "note_015",
    title: "Garden Planning",
    text: "Plant tomatoes in March. Start herbs indoors. Get new soil for flower beds. Research companion planting. Build a small greenhouse.",
    category: "personal",
    createdAt: "2024-01-29T11:00:00.000Z",
  },
  {
    id: "note_016",
    title: "Financial Goals",
    text: "Save 20% of income monthly. Max out retirement contributions. Build 6-month emergency fund. Start investing in index funds.",
    category: "personal",
    createdAt: "2024-01-30T14:00:00.000Z",
  },
  {
    id: "note_017",
    title: "Hobby Ideas to Try",
    text: "Photography, watercolor painting, playing guitar, pottery, woodworking, learning to cook Asian cuisine, stargazing.",
    category: "personal",
    createdAt: "2024-01-31T16:30:00.000Z",
  },
  {
    id: "note_018",
    title: "Daily Affirmations",
    text: "I am capable and strong. I embrace challenges as opportunities. I am grateful for what I have. I deserve happiness and success.",
    category: "personal",
    createdAt: "2024-02-01T07:00:00.000Z",
  },
  {
    id: "note_019",
    title: "Sleep Improvement Tips",
    text: "No screens 1 hour before bed. Keep room cool (18-20°C). Use blackout curtains. Consistent sleep schedule. No caffeine after 2 PM.",
    category: "personal",
    createdAt: "2024-02-02T21:00:00.000Z",
  },
  {
    id: "note_020",
    title: "Car Maintenance Schedule",
    text: "Oil change: every 5000 km. Tire rotation: every 10000 km. Brake inspection: yearly. Air filter: every 20000 km. Next service: March 15.",
    category: "personal",
    createdAt: "2024-02-03T10:30:00.000Z",
  },
  {
    id: "note_021",
    title: "Skincare Routine",
    text: "Morning: cleanser, vitamin C serum, moisturizer, sunscreen. Evening: double cleanse, retinol (3x week), hydrating serum, night cream.",
    category: "personal",
    createdAt: "2024-02-04T08:00:00.000Z",
  },
  {
    id: "note_022",
    title: "Music Playlist Ideas",
    text: "Create playlists for: morning motivation, workout intensity, focus/study, relaxation evening, cooking dinner, road trips.",
    category: "personal",
    createdAt: "2024-02-05T19:00:00.000Z",
  },
  {
    id: "note_023",
    title: "Pet Care Reminders",
    text: "Vet appointment: February 20. Buy more dog food. Schedule grooming. Renew pet insurance. Get new toys for enrichment.",
    category: "personal",
    createdAt: "2024-02-06T09:15:00.000Z",
  },
  {
    id: "note_024",
    title: "Journaling Prompts",
    text: "What am I grateful for today? What challenged me? What did I learn? What could I do better tomorrow? Highlight of the day?",
    category: "personal",
    createdAt: "2024-02-07T20:30:00.000Z",
  },
  {
    id: "note_025",
    title: "Closet Organization",
    text: "Donate clothes not worn in 1 year. Organize by category then color. Invest in quality hangers. Seasonal rotation. Capsule wardrobe goal.",
    category: "personal",
    createdAt: "2024-02-08T13:00:00.000Z",
  },
  {
    id: "note_026",
    title: "Digital Declutter Plan",
    text: "Unsubscribe from newsletters. Delete unused apps. Organize photos into albums. Clean up desktop. Backup important files to cloud.",
    category: "personal",
    createdAt: "2024-02-09T15:45:00.000Z",
  },
  {
    id: "note_027",
    title: "Weekend Trip Packing List",
    text: "Essentials: clothes for 3 days, toiletries, chargers, medications, snacks, water bottle, camera, comfortable walking shoes, light jacket.",
    category: "personal",
    createdAt: "2024-02-10T11:00:00.000Z",
  },

  // Work Notes (28-54)
  {
    id: "note_028",
    title: "Q1 Project Deadlines",
    text: "Website redesign: Feb 28. Mobile app v2.0: March 15. API documentation: March 30. Performance review prep: April 1.",
    category: "work",
    createdAt: "2024-02-11T09:00:00.000Z",
  },
  {
    id: "note_029",
    title: "Meeting Notes - Product Review",
    text: "Discussed user feedback on new features. Priority: fix checkout flow bugs. Consider adding dark mode. Schedule user testing session next week.",
    category: "work",
    createdAt: "2024-02-12T14:30:00.000Z",
  },
  {
    id: "note_030",
    title: "Team Building Ideas",
    text: "Escape room challenge, cooking class, volunteer day, outdoor adventure, trivia night, virtual game session for remote team members.",
    category: "work",
    createdAt: "2024-02-13T11:00:00.000Z",
  },
  {
    id: "note_031",
    title: "Client Feedback Summary",
    text: "Overall positive response. Requests: faster load times, mobile optimization, better search functionality, more payment options.",
    category: "work",
    createdAt: "2024-02-14T16:00:00.000Z",
  },
  {
    id: "note_032",
    title: "Code Review Checklist",
    text: "Check for: proper naming, no console.logs, error handling, unit tests, performance issues, security vulnerabilities, documentation.",
    category: "work",
    createdAt: "2024-02-15T10:30:00.000Z",
  },
  {
    id: "note_033",
    title: "Sprint Retrospective Notes",
    text: "What went well: team collaboration, meeting deadlines. Improvements needed: clearer requirements, better estimation, more testing time.",
    category: "work",
    createdAt: "2024-02-16T15:00:00.000Z",
  },
  {
    id: "note_034",
    title: "Technical Debt List",
    text: "Refactor user authentication module. Update deprecated dependencies. Improve database queries. Add comprehensive logging. Fix CSS inconsistencies.",
    category: "work",
    createdAt: "2024-02-17T09:45:00.000Z",
  },
  {
    id: "note_035",
    title: "Onboarding Improvements",
    text: "Create welcome video. Update documentation. Assign buddy system. Schedule regular check-ins. Improve access to tools and resources.",
    category: "work",
    createdAt: "2024-02-18T13:30:00.000Z",
  },
  {
    id: "note_036",
    title: "Performance Optimization Tasks",
    text: "Implement lazy loading. Optimize images. Enable caching. Minify CSS/JS. Use CDN. Database indexing. Code splitting for large bundles.",
    category: "work",
    createdAt: "2024-02-19T10:00:00.000Z",
  },
  {
    id: "note_037",
    title: "Stakeholder Presentation Outline",
    text: "1. Project overview\n2. Progress update\n3. Key achievements\n4. Challenges faced\n5. Next steps\n6. Q&A session",
    category: "work",
    createdAt: "2024-02-20T14:00:00.000Z",
  },
  {
    id: "note_038",
    title: "Bug Tracking Notes",
    text: "Critical: payment processing error. High: login timeout issues. Medium: UI alignment on mobile. Low: typo on about page.",
    category: "work",
    createdAt: "2024-02-21T11:30:00.000Z",
  },
  {
    id: "note_039",
    title: "API Endpoints to Implement",
    text: "GET /users - list all users\nPOST /users - create user\nGET /users/:id - get single user\nPUT /users/:id - update user\nDELETE /users/:id - delete user",
    category: "work",
    createdAt: "2024-02-22T09:00:00.000Z",
  },
  {
    id: "note_040",
    title: "Security Audit Findings",
    text: "Implement rate limiting. Add input validation. Update SSL certificates. Enable 2FA option. Review access permissions. Encrypt sensitive data.",
    category: "work",
    createdAt: "2024-02-23T16:45:00.000Z",
  },
  {
    id: "note_041",
    title: "Documentation Updates Needed",
    text: "API reference needs examples. Installation guide outdated. Add troubleshooting section. Update screenshots. Create video tutorials.",
    category: "work",
    createdAt: "2024-02-24T10:15:00.000Z",
  },
  {
    id: "note_042",
    title: "Remote Work Best Practices",
    text: "Set dedicated workspace. Maintain regular hours. Over-communicate with team. Take proper breaks. Use video calls when possible.",
    category: "work",
    createdAt: "2024-02-25T08:30:00.000Z",
  },
  {
    id: "note_043",
    title: "Deployment Checklist",
    text: "Run all tests. Check environment variables. Backup database. Update changelog. Notify stakeholders. Monitor for errors. Prepare rollback plan.",
    category: "work",
    createdAt: "2024-02-26T17:00:00.000Z",
  },
  {
    id: "note_044",
    title: "Training Topics for Team",
    text: "TypeScript fundamentals. Testing best practices. Git workflow. Agile methodology. Communication skills. Time management techniques.",
    category: "work",
    createdAt: "2024-02-27T11:00:00.000Z",
  },
  {
    id: "note_045",
    title: "Vendor Evaluation Criteria",
    text: "Price vs value. Technical support quality. Integration capabilities. Scalability. Security compliance. User reviews. Contract flexibility.",
    category: "work",
    createdAt: "2024-02-28T14:30:00.000Z",
  },
  {
    id: "note_046",
    title: "Email Templates to Create",
    text: "Welcome email. Password reset. Order confirmation. Shipping notification. Feedback request. Newsletter template. Re-engagement campaign.",
    category: "work",
    createdAt: "2024-02-29T09:30:00.000Z",
  },
  {
    id: "note_047",
    title: "Accessibility Improvements",
    text: "Add alt text to images. Improve color contrast. Keyboard navigation. Screen reader testing. Focus indicators. ARIA labels.",
    category: "work",
    createdAt: "2024-03-01T13:00:00.000Z",
  },
  {
    id: "note_048",
    title: "Analytics Implementation",
    text: "Track page views. User journey mapping. Conversion funnel. Error tracking. Performance metrics. A/B testing setup. Dashboard creation.",
    category: "work",
    createdAt: "2024-03-02T10:45:00.000Z",
  },
  {
    id: "note_049",
    title: "Interview Questions - Frontend",
    text: "Explain event bubbling. CSS specificity. React hooks usage. Performance optimization. Responsive design approach. Testing strategies.",
    category: "work",
    createdAt: "2024-03-03T15:30:00.000Z",
  },
  {
    id: "note_050",
    title: "Release Notes Template",
    text: "Version number and date. New features list. Improvements made. Bug fixes. Known issues. Upgrade instructions. Deprecation notices.",
    category: "work",
    createdAt: "2024-03-04T09:00:00.000Z",
  },
  {
    id: "note_051",
    title: "KPI Dashboard Metrics",
    text: "User acquisition rate. Customer retention. Revenue growth. Support ticket volume. Page load time. Error rate. User satisfaction score.",
    category: "work",
    createdAt: "2024-03-05T14:00:00.000Z",
  },
  {
    id: "note_052",
    title: "Design System Components",
    text: "Buttons (primary, secondary, ghost). Input fields. Modals. Cards. Navigation. Tables. Alerts. Tooltips. Progress indicators.",
    category: "work",
    createdAt: "2024-03-06T11:30:00.000Z",
  },
  {
    id: "note_053",
    title: "Database Schema Review",
    text: "Normalize user tables. Add indexes to frequently queried columns. Archive old data. Implement soft delete. Review relationships.",
    category: "work",
    createdAt: "2024-03-07T16:00:00.000Z",
  },
  {
    id: "note_054",
    title: "Competitive Analysis Notes",
    text: "Competitor A: better mobile app. Competitor B: lower pricing. Competitor C: more integrations. Our strengths: UX, support, reliability.",
    category: "work",
    createdAt: "2024-03-08T10:00:00.000Z",
  },

  // Ideas Notes (55-80)
  {
    id: "note_055",
    title: "App Idea: Habit Tracker",
    text: "Simple habit tracking with streaks, reminders, and statistics. Gamification elements. Social sharing. Integration with health apps.",
    category: "ideas",
    createdAt: "2024-03-09T19:00:00.000Z",
  },
  {
    id: "note_056",
    title: "Blog Post Topics",
    text: "JavaScript tips for beginners. Remote work productivity. Building side projects. Learning from failures. Tech industry trends.",
    category: "ideas",
    createdAt: "2024-03-10T20:30:00.000Z",
  },
  {
    id: "note_057",
    title: "Side Project: Recipe Sharing",
    text: "Community recipe platform. Users can share, rate, and save recipes. Ingredient-based search. Meal planning feature. Shopping list generator.",
    category: "ideas",
    createdAt: "2024-03-11T15:00:00.000Z",
  },
  {
    id: "note_058",
    title: "Startup Idea: Pet Services",
    text: "Connect pet owners with local services: grooming, walking, sitting, training. Rating system. Booking management. Subscription options.",
    category: "ideas",
    createdAt: "2024-03-12T21:00:00.000Z",
  },
  {
    id: "note_059",
    title: "YouTube Channel Concepts",
    text: "Coding tutorials for beginners. Day in life of developer. Tech review and unboxings. Interview preparation. Building projects live.",
    category: "ideas",
    createdAt: "2024-03-13T18:30:00.000Z",
  },
  {
    id: "note_060",
    title: "Online Course Idea",
    text: "Complete web development bootcamp. From HTML basics to full-stack. Real projects. Certificate. Community support. Job preparation.",
    category: "ideas",
    createdAt: "2024-03-14T14:00:00.000Z",
  },
  {
    id: "note_061",
    title: "E-commerce Niche Ideas",
    text: "Sustainable products. Customizable gifts. Local artisan marketplace. Subscription boxes. Vintage collections. Tech accessories.",
    category: "ideas",
    createdAt: "2024-03-15T16:45:00.000Z",
  },
  {
    id: "note_062",
    title: "Productivity Tool Concept",
    text: "Combine todo list, calendar, and notes. AI-powered prioritization. Time blocking. Focus mode. Integration with popular tools.",
    category: "ideas",
    createdAt: "2024-03-16T10:30:00.000Z",
  },
  {
    id: "note_063",
    title: "Community Building Ideas",
    text: "Discord server for developers. Monthly virtual meetups. Mentorship program. Open source collaboration. Hackathons and challenges.",
    category: "ideas",
    createdAt: "2024-03-17T19:30:00.000Z",
  },
  {
    id: "note_064",
    title: "Newsletter Concept",
    text: "Weekly tech digest. Curated articles and tutorials. Industry news summary. Job opportunities. Tool recommendations. Community spotlight.",
    category: "ideas",
    createdAt: "2024-03-18T08:00:00.000Z",
  },
  {
    id: "note_065",
    title: "Mobile App: Language Exchange",
    text: "Connect language learners worldwide. Video chat feature. Conversation topics. Progress tracking. Cultural exchange. Community events.",
    category: "ideas",
    createdAt: "2024-03-19T17:00:00.000Z",
  },
  {
    id: "note_066",
    title: "SaaS Idea: Team Wiki",
    text: "Internal knowledge base for teams. Easy editing. Search functionality. Access control. Version history. Templates. Integration with Slack.",
    category: "ideas",
    createdAt: "2024-03-20T11:15:00.000Z",
  },
  {
    id: "note_067",
    title: "Creative Writing Prompts App",
    text: "Daily writing prompts. Different genres and styles. Community sharing. Writing streaks. Feedback from other writers. Publishing option.",
    category: "ideas",
    createdAt: "2024-03-21T20:00:00.000Z",
  },
  {
    id: "note_068",
    title: "Fitness App Enhancement Ideas",
    text: "AI workout recommendations. Form check using camera. Social challenges. Integration with wearables. Nutrition tracking. Recovery suggestions.",
    category: "ideas",
    createdAt: "2024-03-22T07:30:00.000Z",
  },
  {
    id: "note_069",
    title: "Educational Game Concept",
    text: "Learn programming through puzzles. Increasing difficulty. Visual coding blocks. Real code output. Achievements and leaderboards.",
    category: "ideas",
    createdAt: "2024-03-23T15:45:00.000Z",
  },
  {
    id: "note_070",
    title: "Smart Home Dashboard",
    text: "Unified control for all smart devices. Energy monitoring. Automation rules. Voice control. Security integration. Family sharing.",
    category: "ideas",
    createdAt: "2024-03-24T12:00:00.000Z",
  },
  {
    id: "note_071",
    title: "Reading List App Features",
    text: "Track books read. Reading goals. Book recommendations. Community reviews. Reading statistics. Integration with e-readers. Book clubs.",
    category: "ideas",
    createdAt: "2024-03-25T18:00:00.000Z",
  },
  {
    id: "note_072",
    title: "Portfolio Website Ideas",
    text: "Interactive timeline. 3D elements. Dark/light mode. Project case studies. Blog integration. Contact chatbot. Downloadable resume.",
    category: "ideas",
    createdAt: "2024-03-26T14:30:00.000Z",
  },
  {
    id: "note_073",
    title: "Freelance Platform Concept",
    text: "Focus on quality over quantity. Vetting process. Escrow payments. Project management tools. Client matching algorithm. Fair commission.",
    category: "ideas",
    createdAt: "2024-03-27T10:00:00.000Z",
  },
  {
    id: "note_074",
    title: "Mental Health App Ideas",
    text: "Mood tracking. Guided meditation. Breathing exercises. Journal prompts. Professional resources. Crisis support. Community support groups.",
    category: "ideas",
    createdAt: "2024-03-28T21:30:00.000Z",
  },
  {
    id: "note_075",
    title: "Event Planning Tool",
    text: "Guest management. Budget tracking. Vendor directory. Timeline creation. Task assignments. Collaboration features. Template events.",
    category: "ideas",
    createdAt: "2024-03-29T11:45:00.000Z",
  },
  {
    id: "note_076",
    title: "Local Business Directory",
    text: "Support local shops and services. Reviews and ratings. Special offers. Loyalty programs. Community events. Direct messaging.",
    category: "ideas",
    createdAt: "2024-03-30T16:15:00.000Z",
  },
  {
    id: "note_077",
    title: "Study Group Finder",
    text: "Connect students studying same subjects. Virtual study rooms. Resource sharing. Scheduling tools. Progress tracking. Tutor matching.",
    category: "ideas",
    createdAt: "2024-03-31T13:00:00.000Z",
  },
  {
    id: "note_078",
    title: "Carbon Footprint Tracker",
    text: "Track daily activities impact. Suggestions for reduction. Community challenges. Offset options. Educational content. Progress visualization.",
    category: "ideas",
    createdAt: "2024-04-01T09:30:00.000Z",
  },
  {
    id: "note_079",
    title: "Skill Bartering Platform",
    text: "Exchange skills without money. Teach what you know, learn what you need. Rating system. Video sessions. Scheduling. Skill verification.",
    category: "ideas",
    createdAt: "2024-04-02T17:45:00.000Z",
  },
  {
    id: "note_080",
    title: "Nostalgia App Concept",
    text: "Daily memories from past years. Photo comparisons then vs now. Milestone reminders. Share with family. Time capsule feature. Memory books.",
    category: "ideas",
    createdAt: "2024-04-03T20:00:00.000Z",
  },
];

// Ensure it's available globally for our FakeAPI
window.initialNotes = INITIAL_NOTES;
